version: "3.3"

services:
  producer:
    build: .
    entrypoint: ["python", "main.py"]
    command: ["run-producer"]
    network_mode: host

  consumer:
    build: .
    entrypoint: ["python", "main.py"]
    command: ["run-consumer"]
    network_mode: host

  web_server:
    build: .
    entrypoint: ["python", "main.py"]
    command: ["run-web"]
    network_mode: host
    ports:
      - 8080:8080

  rabbitmq:
       image: rabbitmq:3.8.12
       environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
       ports:
          - 5672:5672
          - 15672:15672
